### ISSUE TITLE
Frequency being calculated correctly?

### ISSUE THREAD

**Issue by joesbright** [MydonSolutions/BLRI#3]
https://github.com/MydonSolutions/BLRI/blob/7b71a8ee1863ca987e820e56f9e27dabb05d9e42/src/blri/entrypoints/pycorr.py#L254C3-L254C126

If the observation frequency is the central frequency of the band then I think this might calculate the channel frequencies incorrectly? Is this meant to be the central frequency of the first channel? If so then it should be -0.5, and not +0.5. If it's meant to be the start frequency there is no need for the 0.5 at all.

**Comment by radonnachie** [comment]
yeah man this has me constantly double checking myself... let's confirm it!

My interpretation of the standard is that frequencies are always the center of a channel... even the observed frequency, which is the central frequency of the central channel...

The [code that populates the OBSFREQ value](https://github.com/COSMIC-SETI/COSMIC-VLA-PythonLibs/blob/main/src/cosmic/fengines/destination_meta.py#L242-L247) does the following
`lo_bottom = lo_frequency - ((FENCHAN / 2) * CHAN_BW)`
`obs_freq = lo_bottom + (SCHAN + ((NCHAN-1)/2))*CHAN_BW`

Indicating that to get the bottom of the observed frequency range, we sort of undo the last step as follows:
`lo_bottom = obs_freq - ((NCHAN-1)/2)*CHAN_BW`

But the uvh5 'freq_array' is defined to contain the central frequency of the channels, in the [uvh5_memo](https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/main/docs/references/uvh5_memo.pdf), so that needs to be offset half a channel...

`fchan0 = lo_bottom + 0.5*CHAN_BW = obs_freq - (-0.5 +((NCHAN-1)/2))*CHAN_BW`
`fchan0 = obs_freq - ((NCHAN/2) - 1)*CHAN_BW`


Hmmm, that indicates that the current needs to be corrected by `-1.5*CHAN_BW`... I'll spin it up and we can confirm?

**Comment by radonnachie** [comment]
`pip install git+https://github.com/MydonSolutions/BLRI@seticore_freq_fix`

if this proves better then I'll update master and seticore branches...

**Comment by radonnachie** [comment]
Oh, damn, there is a deliberately deferred offset of the frequencies to the center of their channels [here](https://github.com/MydonSolutions/BLRI/blob/7b71a8ee1863ca987e820e56f9e27dabb05d9e42/src/blri/entrypoints/pycorr.py#L257)... so the calculation we're talking about should actually be to the bottom of the observed frequency range:

`bottom_frequency_mhz = obs_freq - ((NCHAN-1)/2)*CHAN_BW = obs_freq - ((NCHAN/2) - 0.5)*CHAN_BW` which is exactly what you said

**Comment by radonnachie** [comment]
observation frequency is the central frequency of the observed band, falling between channels for an even number of channels...

the [line](https://github.com/MydonSolutions/BLRI/blob/7b71a8ee1863ca987e820e56f9e27dabb05d9e42/src/blri/entrypoints/pycorr.py#L254C3-L254C126) you reference calculates the bottom frequency of the observed band, offsetting to the center of the channels is deferred until [later](https://github.com/MydonSolutions/BLRI/blob/7b71a8ee1863ca987e820e56f9e27dabb05d9e42/src/blri/entrypoints/pycorr.py#L307), to adhere to `freq_array` [specification (under sec 3.1)](https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/7d3804fe8cf404221981b483d0bdc7503c969e37/docs/references/uvh5_memo.pdf).

The bottom of the observed frequency band should be `observed_frequency - channel_bandwidth*(nof_channel/2)` you are right!

Thanks!
